In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
my_list = [1, 2, 3, 5, 7, 12]

In [10]:
my_array = np.array(my_list)

In [11]:
my_array

array([ 1,  2,  3,  5,  7, 12])

In [15]:
my_array = np.array([1, 2, 3, 4, 5])

In [16]:
second_element = my_array[1]

In [14]:
second_element

np.int64(2)

In [17]:
last_element = my_array[-1]

In [18]:
last_element

np.int64(5)

In [19]:
subset_array = my_array[1:4]

In [20]:
subset_array

array([2, 3, 4])

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [23]:
arr1

array([[1, 2],
       [3, 4]])

In [24]:
arr2

array([[5, 6],
       [7, 8]])

In [25]:
result = arr1 + arr2
print(result)

[[ 6  8]
 [10 12]]


In [26]:
result = arr1 * arr2
print(result)

[[ 5 12]
 [21 32]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
sum_val = np.sum(arr)

In [29]:
sum_val

np.int64(21)

In [30]:
mean_val = np.mean(arr, axis=1)

In [31]:
mean_val

array([2.5, 3.5, 4.5])

In [32]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
element = arr[0, 2]
print(element)


3


In [36]:
mean_val = np.mean(arr, axis=1)

In [37]:
mean_val

array([2., 5.])

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
row = arr[1, :]
print(row)


[4 5 6]


In [40]:
row = arr[0, :]
print(row)


[1 2 3]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [42]:
rows = arr[[0, 2], :]

In [43]:
rows

array([[1, 2, 3],
       [7, 8, 9]])

In [44]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [45]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
n[0]

array([1, 2, 3])

In [47]:
n[0] = [12, 13, 14]

In [48]:
n

array([[12, 13, 14],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
column = arr[:, 1]
print(column)


[2 5]


In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [54]:
columns = arr[:, [0, 2]]
print(columns)


[[1 3]
 [4 6]
 [7 9]]


In [55]:
columns = arr[[0,1], [0, 2]]
print(columns)

[1 6]


In [56]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [57]:
n[:, 0]

array([1, 4, 7])

In [58]:
n[:, 0] = [12, 13, 14]

In [59]:
n

array([[12,  2,  3],
       [13,  5,  6],
       [14,  8,  9]])

In [60]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
 


In [61]:
n[:,0]

array([1, 4, 7])

In [62]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
n[:, 2] = [0, 1, 2]

In [64]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [69]:
random_integers = np.random.randint(20, size=6)
print(random_integers)


[18 10 19 14  5 17]


In [66]:
random_floats = np.random.random((3, 4))
print(random_floats)


[[0.23738349 0.05747319 0.06041032 0.62580872]
 [0.66692161 0.14947468 0.08089932 0.64945966]
 [0.75894868 0.94744858 0.34905216 0.35156263]]


In [67]:
random_normal = np.random.normal(size=(2, 3, 2))
print(random_normal)


[[[-0.96228772 -0.36165315]
  [-0.07414683  1.64734042]
  [ 0.62136418  0.0444745 ]]

 [[-0.42341239 -0.43769359]
  [ 1.22842842 -1.81202751]
  [ 0.93745528  0.62261453]]]


In [70]:
np.random.rand(5, 2)

array([[0.96138708, 0.3518333 ],
       [0.12599455, 0.83524825],
       [0.6051288 , 0.89120843],
       [0.42741609, 0.23502228],
       [0.62786796, 0.93916019]])

In [71]:
random_normal = np.random.normal(size=(2, 3, 2))
print(random_normal)

[[[ 1.4699362  -0.27341523]
  [ 0.50920842 -0.28745591]
  [ 0.08433398  1.58952203]]

 [[-0.41030362  1.06305987]
  [ 0.79898546 -0.78861822]
  [ 0.27464984  0.80769163]]]


In [72]:
np.random.seed(2)
np.random.randn(5, 2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [73]:
np.random.seed(2)
100 * np.random.rand(5, 2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [74]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))


array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [75]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [76]:
result = arr1 + arr2
print(result)


[5 7 9]


In [77]:
result = arr1 - arr2
print(result)


[-3 -3 -3]


In [78]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
 
# Element-wise multiplication
result = arr1 * arr2
print(result)


[ 4 10 18]


In [79]:
result = arr1 / arr2
print(result)


[0.25 0.4  0.5 ]


In [80]:
arr = np.array([0, np.pi/2, np.pi])
result = np.sin(arr)
print(result)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [81]:
result = np.exp(arr)
print(result)


[ 1.          4.81047738 23.14069263]


In [82]:
a = np.arange(5)

In [83]:
a

array([0, 1, 2, 3, 4])

In [84]:
a + 1

array([1, 2, 3, 4, 5])

In [85]:
a * 2

array([0, 2, 4, 6, 8])

In [86]:
a * 100

array([  0, 100, 200, 300, 400])

In [87]:
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

In [88]:
b = (10 + (a * 2)) ** 2 / 100
b


array([1.  , 1.44, 1.96, 2.56, 3.24])

In [89]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [90]:
arr = np.array([1, 2, 3, 4, 5])
 
# Compare elements with 3
result = arr > 3
print(result)


[False False False  True  True]


In [91]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])
 
# Compare elements of arr1 and arr2
result = arr1 == arr2
print(result)


[False  True False]


In [92]:
arr = np.array([1, 2, 3, 4, 5])

In [94]:
result = (arr > 2) | (arr < 5)
print(result)


[ True  True  True  True  True]


In [97]:
a = np.arange(5)
b = (10 + (a * 2)) ** 2 / 100
# compare numbers element-wise
a >= 2


array([False, False,  True,  True,  True])

In [96]:
a > b

array([False, False,  True,  True,  True])

In [98]:
a[a > b]

array([2, 3, 4])

In [99]:
a[2], a[3], a[4]

(np.int64(2), np.int64(3), np.int64(4))

In [100]:
a.min()

np.int64(0)

In [101]:
a.max()

np.int64(4)

In [102]:
a.sum()

np.int64(10)

In [103]:
a.mean()

np.float64(2.0)

In [104]:
a.std()

np.float64(1.4142135623730951)

In [105]:
n = np.array([
   [12, 13,  0],
    [ 4,  5,  1],
    [ 7,  8,  2]
])


In [106]:
n.sum()

np.int64(52)

In [107]:
n.min()

np.int64(0)

In [108]:
n.max()

np.int64(13)

In [109]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [110]:
import sys
!{sys.executable} -m pip install pandas


   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 4.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.5 MB 4.3 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.5 MB 4.7 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.5 MB 5.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 5.4 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.5 MB 5.7 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.5 MB 6.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 6.0 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 5.1 MB/s eta 0:00:00


In [111]:
import pandas as pd

In [112]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'


_IncompleteInputError: incomplete input (2427467648.py, line 11)

In [113]:
pd.DataFrame(data)

NameError: name 'data' is not defined

In [114]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP']

In [115]:
pd.DataFrame(data)

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [116]:
df = pd.DataFrame(data, columns = columns)
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [117]:
df.head()

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [118]:
df.head(2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [119]:
make_series = pd.Series(df['Make'])

In [120]:
make_series

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [121]:
nissan_cars = make_series[make_series == 'Nissan']

In [122]:
nissan_cars 

0    Nissan
4    Nissan
Name: Make, dtype: object

In [123]:
msrp_series = pd.Series(df['MSRP'])

In [124]:
msrp_series

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [125]:
average_msrp = msrp_series.mean()

In [126]:
average_msrp

np.float64(30186.0)

In [127]:
def convert_to_euros(value):
    return value * 0.85
 
msrp_in_euros = msrp_series.apply(convert_to_euros)


In [128]:
msrp_in_euros 

0     1700.0
1    23077.5
2    46741.5
3    29282.5
4    27489.0
Name: MSRP, dtype: float64

In [129]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [130]:
df.Model

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [131]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [132]:
df[['Make', 'Model', 'MSRP']]

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [133]:
df['id'] = [1, 2, 3, 4, 5]

In [134]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [135]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [136]:
df['id'] = [10, 20, 30, 40, 50]

In [137]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000  10  
1         Sedan  27150  20  
2   convertible  54990  30  
3       4dr SUV  34450  40  
4        Pickup  32340  50

In [138]:
del df['id']
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [139]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [140]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [141]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [142]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [143]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [144]:
df.loc[['b', 'c']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [145]:
df.iloc[[1, 2, 4]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990  
e        Pickup  32340

In [146]:
df.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [147]:
df = df.reset_index(drop=True)
df


Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [148]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [149]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [150]:
df.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [151]:
df.Year >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [152]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [153]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [155]:
df = df.reset_index(drop=False)

In [156]:
df

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [157]:
df = df.reset_index(drop=True)

In [158]:
df

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [159]:
df[df.Year >= 2015]

index     Make     Model  Year  Engine HP  Engine Cylinders  \
1     b  Hyundai    Sonata  2017        NaN                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
1         AUTOMATIC         Sedan  27150  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [160]:
df[
    df.Make == 'Nissan'
]


index    Make     Model  Year  Engine HP  Engine Cylinders  \
0     a  Nissan    Stanza  1991      138.0                 4   
4     e  Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
4            MANUAL        Pickup  32340

In [161]:
df[
    (df.Make == 'Nissan') & (df.Year > 2015)
]


index    Make     Model  Year  Engine HP  Engine Cylinders  \
4     e  Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
4            MANUAL        Pickup  32340

In [162]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [163]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [164]:
df['Vehicle_Style'].str.replace(' ','_')

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [165]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.lower().str.replace(' ','_')
df


index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr_suv  34450  
4            MANUAL        pickup  32340

In [166]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [167]:
df.MSRP.min()

np.int64(2000)

In [168]:
df.MSRP.max()

np.int64(54990)

In [169]:
df.MSRP.mean()

np.float64(30186.0)

In [170]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [171]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [172]:
df.Make.nunique()

4

In [173]:
df.nunique()

index                5
Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [174]:
df.Year.unique()

array([1991, 2017, 2010])

In [175]:
df.isnull()

index   Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False  False      False             False              False   
1  False  False  False  False       True             False              False   
2  False  False  False  False      False             False              False   
3  False  False  False  False      False             False              False   
4  False  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [176]:
df.isnull().sum()

index                0
Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [177]:
df.groupby('Transmission Type').MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [178]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

In [179]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [180]:
df.to_dict(orient='records')

[{'index': 'a',
  'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'index': 'b',
  'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'index': 'c',
  'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'index': 'd',
  'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'index': 'e',
  'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 323